# Generated by Django 5.1.2 on 2024-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Process', 'In Process'), ('Sent', 'Sent'), ('Completed', 'Completed')], default='new', max_length=20),
        ),
    ]
